export const GET_BOOK_LIST = 'GET_BOOK_LIST';
export const CLEAR_BOOK_LIST = 'CLEAR_BOOK_LIST';
export const SET_SEARCH_VAL = 'SET_SEARCH_VAL';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

// Error
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

// myBookList
export const ADD_TO_MY_BOOKLIST = 'ADD_TO_MY_BOOKLIST';
export const REMOVE_FROM_MY_BOOKLIST = 'ADD_TO_MY_BOOKLIST';
export const CREATE_NEW_MY_BOOKLIST = 'CREATE_NEW_MY_BOOKLIST';
export const CREATE_NEW_MY_BOOKLIST_FAIL = 'CREATE_NEW_MY_BOOKLIST_FAIL';
export const CREATE_NEW_MY_BOOKLIST_SUCCESS = 'CREATE_NEW_MY_BOOKLIST_SUCCESS';
export const DELETE_MY_BOOKLIST = 'DELETE_MY_BOOKLIST';
export const GET_MY_BOOKLIST_REQUEST = 'GET_MY_BOOKLIST_REQUEST';
export const GET_MY_BOOKLIST_SUCCESS = 'GET_MY_BOOKLIST_SUCCESS';
export const GET_MY_BOOKLIST_FAIL = 'GET_MY_BOOKLIST_FAIL';
export const CLEAR_MY_BOOKLIST = 'CLEAR_MY_BOOKLIST';
